# Generated by Django 4.1.3 on 2022-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TheEvent", "0002_rename_eventview_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="space_capacity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
